Problem : Callback hell (Callback inside a callback..)
Solution : Async-Await

Note : We have to create a function and mark it async to use async-await.


Error Handling : try-catch